# Uncomment this line to define a global platform for your project
platform :ios, "10.0"

inhibit_all_warnings!
use_frameworks!

target :ConqueringReactiveSwift do
	pod 'ReactiveCocoa', '~> 6.0'
end

